worker_processes auto;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    gzip off;

    server {
        listen 8446 ssl;
        listen 8446 quic reuseport;
        http3 on;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;
        ssl_protocols TLSv1.3;

        add_header Alt-Svc 'h3=":8446"; ma=86400' always;
        add_header X-ProtocolLab-Target 'nginx-http3' always;

        location = /plaintext {
            default_type text/plain;
            return 200 'Hello, World!';
        }

        location = /json {
            default_type application/json;
            return 200 '{"message":"Hello, World!"}';
        }
    }
}
